coverage:
  precision: 0
  round: down
  status:
    project:
      default:
        enabled: yes
        target: 95%
        threshold: 1%
    patch:
      default:
        target: auto

comment:
  layout: "diff"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
