language: python
cache: pip
python:
  - "3.6"
  - "3.7-dev"
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip install codecov tox-travis
script:
  - tox
after_success:
  - codecov
notifications:
  email: false
env:
  - COLUMNS=80
