sudo: false

language: python

python:
  - 3.6
  - nightly

install:
  - pip install '.[ci]'

script:
  - nosetests -v --with-coverage --cover-package=sample_sheet --cover-xml

after_success:
  - codecov

notifications:
  email: false

env:
  - COLUMNS=80
