#!/usr/bin/env sh
nosetests \
  -v \
  --progressive-with-bar \
  --with-coverage \
  --with-doctest \
  --doctest-tests \
  --cover-package=sample_sheet \
  --with-progressive \
  $(basename "${0}/tests") \
  "${@}"
