#!/usr/bin/env sh
nosetests \
  -v \
  --progressive-with-bar \
  --with-coverage \
  --with-doctest \
  --doctest-tests \
  --cover-package=sample_sheet \
  --with-progressive \
  "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" \
  "${@}"
