#!/usr/bin/env python3
import click

from sample_sheet import SampleSheet


@click.group(context_settings=dict(help_option_names=['-h', '--help']))
def cli():
    pass


@cli.command()
@click.argument('path')
def summary(path):
    """Pretty print a sample sheet"""
    print(SampleSheet(path))


if __name__ == '__main__':
    cli()
